# Generated by Django 4.2.24 on 2025-12-15 21:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="documents_verified",
            field=models.BooleanField(default=False, verbose_name="Dokumente geprüft"),
        ),
        migrations.AddField(
            model_name="user",
            name="onboarding_completed",
            field=models.BooleanField(
                default=False, verbose_name="Onboarding abgeschlossen"
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="onboarding_step",
            field=models.IntegerField(
                choices=[
                    (1, "Profil ausfüllen"),
                    (2, "Dokumente hochladen"),
                    (3, "Tarif wählen"),
                    (4, "Zahlung einrichten"),
                    (5, "Abgeschlossen"),
                ],
                default=1,
                verbose_name="Onboarding-Schritt",
            ),
        ),
    ]
