# Generated by Django 4.2.24 on 2026-01-02 12:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0003_paypal"),
    ]

    operations = [
        migrations.CreateModel(
            name="ConsentLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "consent_type",
                    models.CharField(
                        choices=[
                            ("medical_data", "Medizinische Daten (Art. 9 DSGVO)"),
                            ("terms", "AGB"),
                            ("privacy", "Datenschutzerklärung"),
                            ("marketing", "Marketing"),
                            ("cookies_functional", "Funktionale Cookies"),
                            ("cookies_analytics", "Analyse-Cookies"),
                        ],
                        max_length=30,
                        verbose_name="Art der Einwilligung",
                    ),
                ),
                ("granted", models.BooleanField(default=True, verbose_name="Erteilt")),
                (
                    "consent_version",
                    models.CharField(
                        default="1.0",
                        max_length=20,
                        verbose_name="Version der Einwilligung",
                    ),
                ),
                (
                    "ip_address",
                    models.GenericIPAddressField(
                        blank=True, null=True, verbose_name="IP-Adresse"
                    ),
                ),
                ("user_agent", models.TextField(blank=True, verbose_name="User Agent")),
                (
                    "consent_text_hash",
                    models.CharField(
                        blank=True,
                        help_text="SHA256 hash для проверки изменений текста",
                        max_length=64,
                        verbose_name="Hash des Einwilligungstexts",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Erteilt am"),
                ),
                (
                    "withdrawn_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Widerrufen am"
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="consent_logs",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Benutzer",
                    ),
                ),
            ],
            options={
                "verbose_name": "Einwilligungsprotokoll",
                "verbose_name_plural": "Einwilligungsprotokolle",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["user", "consent_type"],
                        name="accounts_co_user_id_971819_idx",
                    ),
                    models.Index(
                        fields=["consent_type", "created_at"],
                        name="accounts_co_consent_4e4edb_idx",
                    ),
                ],
            },
        ),
    ]
