# Generated by Django 4.2.24 on 2025-12-14 13:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("subscriptions", "__first__"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="BlisterOrder",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "order_number",
                    models.CharField(
                        db_index=True,
                        max_length=50,
                        unique=True,
                        verbose_name="Bestellnummer",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Ausstehend"),
                            ("processing", "In Bearbeitung"),
                            ("pharmacy_check", "Apothekenprüfung"),
                            ("packaging", "Verpackung"),
                            ("shipped", "Versendet"),
                            ("delivered", "Zugestellt"),
                            ("canceled", "Storniert"),
                        ],
                        default="pending",
                        max_length=20,
                        verbose_name="Status",
                    ),
                ),
                ("period_start", models.DateField(verbose_name="Zeitraum von")),
                ("period_end", models.DateField(verbose_name="Zeitraum bis")),
                (
                    "shipping_name",
                    models.CharField(max_length=255, verbose_name="Empfängername"),
                ),
                (
                    "shipping_street",
                    models.CharField(max_length=255, verbose_name="Straße"),
                ),
                (
                    "shipping_postal_code",
                    models.CharField(max_length=10, verbose_name="PLZ"),
                ),
                (
                    "shipping_city",
                    models.CharField(max_length=100, verbose_name="Stadt"),
                ),
                (
                    "shipping_country",
                    models.CharField(default="DE", max_length=2, verbose_name="Land"),
                ),
                (
                    "pharmacy_notes",
                    models.TextField(blank=True, verbose_name="Apothekennotizen"),
                ),
                (
                    "customer_notes",
                    models.TextField(blank=True, verbose_name="Kundennotizen"),
                ),
                (
                    "processed_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Bearbeitet am"
                    ),
                ),
                (
                    "shipped_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Versendet am"
                    ),
                ),
                (
                    "delivered_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Zugestellt am"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "subscription",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="balirate_orders",
                        to="subscriptions.subscription",
                        verbose_name="Abonnement",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="balirate_orders",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Benutzer",
                    ),
                ),
            ],
            options={
                "verbose_name": "Blister-Bestellung",
                "verbose_name_plural": "Blister-Bestellungen",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Shipment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "tracking_number",
                    models.CharField(
                        db_index=True, max_length=50, verbose_name="Sendungsnummer"
                    ),
                ),
                (
                    "carrier",
                    models.CharField(
                        default="DHL",
                        max_length=50,
                        verbose_name="Versanddienstleister",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("label_created", "Etikett erstellt"),
                            ("picked_up", "Abgeholt"),
                            ("in_transit", "Unterwegs"),
                            ("out_for_delivery", "Zustellung läuft"),
                            ("delivered", "Zugestellt"),
                            ("failed", "Zustellung fehlgeschlagen"),
                            ("returned", "Zurückgesendet"),
                        ],
                        default="label_created",
                        max_length=20,
                        verbose_name="Status",
                    ),
                ),
                (
                    "tracking_url",
                    models.URLField(blank=True, verbose_name="Tracking-URL"),
                ),
                (
                    "weight",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=5,
                        null=True,
                        verbose_name="Gewicht (kg)",
                    ),
                ),
                (
                    "estimated_delivery",
                    models.DateField(
                        blank=True,
                        null=True,
                        verbose_name="Voraussichtliche Zustellung",
                    ),
                ),
                (
                    "actual_delivery",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Tatsächliche Zustellung"
                    ),
                ),
                (
                    "last_tracking_update",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Letztes Tracking-Update"
                    ),
                ),
                (
                    "tracking_events",
                    models.JSONField(
                        blank=True, default=list, verbose_name="Tracking-Events"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "order",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="shipment",
                        to="deliveries.blisterorder",
                        verbose_name="Bestellung",
                    ),
                ),
            ],
            options={
                "verbose_name": "Sendung",
                "verbose_name_plural": "Sendungen",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Medication",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=255, verbose_name="Medikamentenname"),
                ),
                ("dosage", models.CharField(max_length=100, verbose_name="Dosierung")),
                (
                    "pzn",
                    models.CharField(blank=True, max_length=20, verbose_name="PZN"),
                ),
                ("morning", models.BooleanField(default=False, verbose_name="Morgens")),
                ("noon", models.BooleanField(default=False, verbose_name="Mittags")),
                ("evening", models.BooleanField(default=False, verbose_name="Abends")),
                ("night", models.BooleanField(default=False, verbose_name="Nachts")),
                (
                    "instructions",
                    models.TextField(blank=True, verbose_name="Einnahmehinweise"),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="Aktiv")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="medications",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Benutzer",
                    ),
                ),
            ],
            options={
                "verbose_name": "Medikament",
                "verbose_name_plural": "Medikamente",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="BlisterOrderItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "medication_name",
                    models.CharField(max_length=255, verbose_name="Medikamentenname"),
                ),
                (
                    "medication_dosage",
                    models.CharField(max_length=100, verbose_name="Dosierung"),
                ),
                (
                    "medication_pzn",
                    models.CharField(blank=True, max_length=20, verbose_name="PZN"),
                ),
                ("morning", models.BooleanField(default=False, verbose_name="Morgens")),
                ("noon", models.BooleanField(default=False, verbose_name="Mittags")),
                ("evening", models.BooleanField(default=False, verbose_name="Abends")),
                ("night", models.BooleanField(default=False, verbose_name="Nachts")),
                (
                    "quantity",
                    models.PositiveIntegerField(default=1, verbose_name="Menge"),
                ),
                (
                    "medication",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="order_items",
                        to="deliveries.medication",
                        verbose_name="Medikament",
                    ),
                ),
                (
                    "order",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="items",
                        to="deliveries.blisterorder",
                        verbose_name="Bestellung",
                    ),
                ),
            ],
            options={
                "verbose_name": "Bestellposition",
                "verbose_name_plural": "Bestellpositionen",
            },
        ),
    ]
